CREATE TABLE "ADDRESS" (
  "STREET"         VARCHAR NOT NULL,
  "CITY"           VARCHAR NOT NULL,
  "UUID"           VARCHAR NOT NULL PRIMARY KEY,
  "INSERTED_AT"    TIMESTAMP NOT NULL,
  "UPDATED_AT"     TIMESTAMP NOT NULL
);

CREATE TABLE "PERSON" (
  "NAME"           VARCHAR NOT NULL,
  "AGE"            INT NOT NULL,
  "ADDRESS_UUID"   VARCHAR NOT NULL,
  "UUID"           VARCHAR NOT NULL PRIMARY KEY,
  "INSERTED_AT"    TIMESTAMP NOT NULL,
  "UPDATED_AT"     TIMESTAMP NOT NULL,

  CONSTRAINT "ADDRESS_FK" FOREIGN KEY ("ADDRESS_UUID")
    REFERENCES "ADDRESS" ("UUID") ON UPDATE RESTRICT ON DELETE RESTRICT
);
